---
title: "Conclusion"
author: "René van Son"
bibliography: references.bib
csl: apa.csl
---

```{=html}
<style>
body {
text-align: justify;
font-family: Times;
}
</style>
```

# Conclusion

In this research, I have attempted to show that taking a social network perspective is beneficial when trying to understand collaboration networks. I have done so by focusing on interdisciplinarity, and by trying to disentangle the various selection processes at work in a social network. The analysis has shown that the network becomes more clustered over time (RQ1). As mentioned above, this is also due to the nature of the data (which is essentially sparser in wave 1 than in wave 2). However, not only did the network become more clustered, the network visualizations and descriptives showed (with caution) that there is a relation between interdisciplinarity and network clustering (RQ2). The Siena models showed the selection processes underlying the network change, where it became clear (among other things) that people with many in-degrees will get even more in-degree and that interdisciplinary authors preferably *send* ties to other interdisciplinary authors (if they send ties). As such, these micro-level selection processes (partly) determined network outcome.

It seems that these findings are thus in line with the argumentation provided by @spence2024and, who claimed that adopting interdisciplinary research programs is beneficial for early-career researchers. The findings are also in line with the preferential attachment theory, as it became clear that tie receivers were increasingly receiving more ties [@khan2018online; @capocci2006preferential]. How this in-degree popularity exactly relates to interdisciplinarity remains an open question, though, and is fuel for future studies.

Next to the obvious benefits of social network analysis and this research, there are also the downsides. Working with collaboration data can be quite restrictive. For example, the sample here contained only sociology and political science departments. Therefore, collaborations with researchers outside these departments could not be shown in our network. This touches on the problem of how exponentially fast networks get bigger and, subsequently, how time-consuming/expensive it is to collect network data.

Further research will have to determine the specific network *influences* on collaboration networks, as this research was primarily concerned with selection processes. For example, it might be worthwhile to consider how network-properties influence actors to become more or less interdisciplinary. It could also be beneficial to further delve into the specifics of collaboration preferences: do all interdisciplinary researchers favor other interdisciplinary oriented researchers, or is this something specific for the social sciences? What about the researchers who are stragglers? Are they 'forced' by the network to join, or do they remain in their own disciplinary cages?
