---
title: "Theory"
author: "René van Son"
bibliography: references.bib
csl: apa.csl
---

```{=html}
<style>
body {
text-align: justify;
font-family: Times;
}
</style>
```
# Theory

## Conceptualization of Discipline and Interdisciplinarity

Before developing any kind of framework for interdisciplinarity, it is first necessary to conceptualize 'discipline' itself. In this study, I follow the definition of discipline as given by @zheng2023research. According to them, a discipline is defined as "the narrowness of focus or boundaries between different knowledge specializations", and is synonoymous with "research fields" (p. 2). However, where these boundaries start and end is often rather unclear. In the broadest sense, disciplines could be defined as departments (what @zheng2023research call 'institutions'). In this case, the social sciences, humanities and natural sciences would be categorized as different disciplines. Collaboration *between* any of these disciplines would constitute interdisciplinarity, whereas collaboration *within* these disciplines would not. Obviously, this definition is overly general, leaving little room to further define unique principles, methods, epistemologies and assumptions that differ within these rather broad categories. Sociology and psychology, while having some aspects in common which makes them belong to the social sciences, can hardly be said to be the same *discipline.* So, to capture these differences, it is neccessary to adopt a more fine-grained perspective on what constitutes a discipline. In the research at hand, as will be explicated below, this will be called a 'field'.

To complicate things further, interdisciplinarity can be defined at multiple levels. For example a *work* can be said to be interdisciplinary in nature based on the 'spread' of citations. An *author/scholar* can be said to be interdisciplinary based on his/her works. A *journal* can be said to be interdisciplinary based on either the works it publishes or the authors/scholars they allow to be published @zheng2023research. For the research at hand, however, I will focus on interdisciplinarity at the author level, based on the diversity of their published works.

Additionally, beyond the various levels that define interdisciplinarity, the concept itself remains somewhat elusive, both in terms of definitions and measurements [@haines2011; @haythornthwaite2006learning]. *Definitions* of interdisciplinarity are often conflated with (among others) transdisciplinarity and multidisciplinarity [@haines2011], with insufficient distinction made between these related yet different concepts. For example, in arguing for the benefits of interdisciplinary research of the social and natural sciences, @barthel2017interdisciplinary defined three upwardly scaling modes of collaboration: cross-disciplinarity, multi-disciplinarity and interdisciplinarity. *Measures* of interdisciplinarity may include individual interdisciplinarity (i.e. the interdisciplinary background of a researcher) or collective interdisciplinarity (i.e. the interactions of researchers from different disciplines). Moreover, interdisciplinarity can be measured by means of bibliometric analysis, which may result in interdisciplinarity-scores based on citation diversity (i.e. works cited encompass a wide variety of disciplines) [@locatelli2021collective], journal-analysis (i.e. journals that identify as interdisciplinary) [@barthel2017interdisciplinary; @zheng2023research], etc.

## Hypotheses

Taking the theoretical considerations above into account, I develop three (????) hypotheses.

First, relating to the structure of the networks @SNASS, I expect the network to display a higher degree of clustering over time. This expectation is fueled by the idea of 'preferential attachment' @khan2018online; @capocci2006preferential, where persons with more existing relations are more likely to enter in *even more* relations. This is also known as the principle of "the rich getting richer", and leads to the development of scale-free networks, with a few highly connected persons and many less-connected persons @khan2018online. That is to say, I expect that the collaboration network evolves from a network with an evenly distributed amount of connected scholars to a network with several scholars who are more central:

H1: *the collaboration network becomes more clustered over time, i.e. the network at t2 will show a higher clustering than the network at t1.*

Next, to explain this macro-level change by means of micro-level mechanisms of interdisciplinarity, I further draw on the principle of clustering and transitivity @haines2011; @freeman2002centrality, which assumes that central positions in a network are beneficial to persons (in this research: authors), as they allow people to adopt a more important 'function' in the network. Relating this to interdisciplinarity, one would expect that people with a high degree of interdisciplinarity would occupy a central role in the collaboration network, as they effectively function as a hub for information and knowledge distribution across multiple disciplines.

H2: *collaboration networks become more clustered around scholars with high levels of interdisciplinarity, i.e. the network at t2 will show the presence of scholars with high indegrees and high levels of interdisciplinarity*

Lastly, following the logic of centralization based on interdisciplinarity, one could also make the argument that, even though interdisciplinary researchers may receive many in-degrees, this

# References
